// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth-callback" | "/dashboard" | "/dashboard/[workspaceId]" | "/invite/[token]"
type AppRouteHandlerRoutes = "/api/auth/discord" | "/api/auth/discord/callback" | "/api/auth/github" | "/api/auth/github/callback" | "/api/auth/login" | "/api/auth/me" | "/api/auth/register" | "/api/github/repos" | "/api/webhooks/discord" | "/api/webhooks/github" | "/api/webhooks/whatsapp" | "/api/workspaces" | "/api/workspaces/[workspaceId]" | "/api/workspaces/[workspaceId]/ai-analyze" | "/api/workspaces/[workspaceId]/alerts" | "/api/workspaces/[workspaceId]/bus-factor" | "/api/workspaces/[workspaceId]/collaborators" | "/api/workspaces/[workspaceId]/commits/summarize" | "/api/workspaces/[workspaceId]/dashboard" | "/api/workspaces/[workspaceId]/heuristics" | "/api/workspaces/[workspaceId]/insights/generate" | "/api/workspaces/[workspaceId]/invite" | "/api/workspaces/[workspaceId]/members" | "/api/workspaces/[workspaceId]/messages" | "/api/workspaces/[workspaceId]/repo" | "/api/workspaces/[workspaceId]/todos" | "/api/workspaces/[workspaceId]/todos/generate" | "/api/workspaces/invite/join"
type PageRoutes = "/_document"
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/_document": {}
  "/api/auth/discord": {}
  "/api/auth/discord/callback": {}
  "/api/auth/github": {}
  "/api/auth/github/callback": {}
  "/api/auth/login": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/github/repos": {}
  "/api/webhooks/discord": {}
  "/api/webhooks/github": {}
  "/api/webhooks/whatsapp": {}
  "/api/workspaces": {}
  "/api/workspaces/[workspaceId]": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/ai-analyze": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/alerts": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/bus-factor": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/collaborators": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/commits/summarize": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/dashboard": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/heuristics": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/insights/generate": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/invite": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/members": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/messages": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/repo": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/todos": { "workspaceId": string; }
  "/api/workspaces/[workspaceId]/todos/generate": { "workspaceId": string; }
  "/api/workspaces/invite/join": {}
  "/auth-callback": {}
  "/dashboard": {}
  "/dashboard/[workspaceId]": { "workspaceId": string; }
  "/invite/[token]": { "token": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
