// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type PagesPageConfig = {
  default: React.ComponentType<any> | ((props: any) => React.ReactNode | Promise<React.ReactNode> | never | void)
  getStaticProps?: (context: any) => Promise<any> | any
  getStaticPaths?: (context: any) => Promise<any> | any
  getServerSideProps?: (context: any) => Promise<any> | any
  getInitialProps?: (context: any) => Promise<any> | any
  /**
   * Segment configuration for legacy Pages Router pages.
   * Validated at build-time by parsePagesSegmentConfig.
   */
  config?: {
    amp?: boolean | 'hybrid' | string // necessary for JS
    maxDuration?: number
    runtime?: 'edge' | 'experimental-edge' | 'nodejs' | string // necessary unless config is exported as const
    regions?: string[]
  }
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/auth-callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth-callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth-callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/[workspaceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[workspaceId]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/[workspaceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invite/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/invite/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/discord/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/discord/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/discord/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/discord/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/discord">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/discord/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/github/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/github/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/github/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/github/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/github">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/github/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/github/repos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/github/repos">> = Specific
  const handler = {} as typeof import("../../src/app/api/github/repos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/discord/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/discord">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/discord/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/github/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/github">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/github/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/whatsapp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/whatsapp">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/whatsapp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/ai-analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/ai-analyze">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/ai-analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/bus-factor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/bus-factor">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/bus-factor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/collaborators/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/collaborators">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/collaborators/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/commits/summarize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/commits/summarize">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/commits/summarize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/heuristics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/heuristics">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/heuristics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/insights/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/insights/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/insights/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/members">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/repo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/repo">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/repo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/todos/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/todos/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/todos/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/[workspaceId]/todos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/[workspaceId]/todos">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/[workspaceId]/todos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/invite/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces/invite/join">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/invite/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workspaces/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspaces">> = Specific
  const handler = {} as typeof import("../../src/app/api/workspaces/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/pages/_document.tsx
{
  type __IsExpected<Specific extends PagesPageConfig> = Specific
  const handler = {} as typeof import("../../src/pages/_document.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}



// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
